# Copyright Rob Gage 2025

[package]
name = "pup_parsers"
version = "0.0.0"
license = "MIT"
description = "Pretty Understandable Parsers"
readme = "README.md"
repository = "https://github.com/rob-gage/pup"
edition = "2021"

[dependencies]
